// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49t7lULsZbKrykgkNSTO8PyRyyrm1h0U',
    appId: '1:749501480484:web:df3d3faf97f60115a3a2b1',
    messagingSenderId: '749501480484',
    projectId: 'chatapptute-56f2e',
    authDomain: 'chatapptute-56f2e.firebaseapp.com',
    storageBucket: 'chatapptute-56f2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT66BIthfmi_8ykmRBFief0tELYoeT33I',
    appId: '1:749501480484:android:bf396352befdf55ba3a2b1',
    messagingSenderId: '749501480484',
    projectId: 'chatapptute-56f2e',
    storageBucket: 'chatapptute-56f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1IfhJeAXXYxywyvk7llyGDIASukMnyo',
    appId: '1:749501480484:ios:fabbe436b9adaef8a3a2b1',
    messagingSenderId: '749501480484',
    projectId: 'chatapptute-56f2e',
    storageBucket: 'chatapptute-56f2e.appspot.com',
    iosBundleId: 'com.example.meowchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD1IfhJeAXXYxywyvk7llyGDIASukMnyo',
    appId: '1:749501480484:ios:80d659331259fc0ea3a2b1',
    messagingSenderId: '749501480484',
    projectId: 'chatapptute-56f2e',
    storageBucket: 'chatapptute-56f2e.appspot.com',
    iosBundleId: 'com.example.meowchat.RunnerTests',
  );
}
